
apply plugin: 'java'

def fineVersion = '11.0-FINAL-SNAPSHOT'

def finebiVersion = '7.0-RELEASE-SNAPSHOT' //finebi 7.0 release branch
def finePolarVersion ='RELEASE-BI-SNAPSHOT' //finebi 7.0 corresponding polar branch

//def finebiVersion = '6.1-RELEASE-SNAPSHOT' //finebi 6.1 release branch
//def finePolarVersion ='6.1.9-PERSIST-BI-SNAPSHOT' //finebi 6.1 corresponding polars branch

group = 'com.fr.plugin'
version = '11.0'
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
repositories {
    mavenLocal()
    maven {
        url = uri('https://mvn.fanruan.com/repository/maven-public/')
    }

    maven {
        url = uri('http://repo.maven.apache.org/maven2')
    }
}

task install(type: Copy) {
    into "webroot/WEB-INF/lib"
    from configurations.runtimeClasspath
}

dependencies {
    implementation files("${System.getProperty('java.home')}/../lib/tools.jar")
    implementation 'com.fr.third:fine-third:' + fineVersion
    implementation 'com.fr.activator:fine-activator:' + fineVersion
    implementation 'com.fr.core:fine-core:' + fineVersion
    implementation 'com.fr.cbb:fine-cbb:' + fineVersion
    implementation 'com.fr.webui:fine-webui:' + fineVersion
    implementation 'com.fr.datasource:fine-datasource-api:4.1-SNAPSHOT'
    implementation 'com.fr.decision:fine-decision:' + fineVersion
    implementation 'com.fr.report:fine-report-designer:' + fineVersion
    implementation 'com.fr.decision:fine-decision-report:' + fineVersion
    implementation 'com.fr.schedule:fine-schedule:' + fineVersion
    implementation 'com.fr.schedule:fine-schedule-report:' + fineVersion
    implementation 'com.fr.intelligence:fine-swift:' + fineVersion
    implementation 'com.fr.intelligence:fine-accumulator:' + fineVersion
    implementation 'com.fr.report:fine-report-engine:' + fineVersion
    implementation 'com.finebi:fine-bi-engine-third:' + finebiVersion
    implementation 'com.finebi:fine-bi-adapter:' + finebiVersion
    implementation 'com.finebi:fine-bi-engine-spider:' + finebiVersion
    implementation 'com.finebi:fine-bi-foundation:' + finebiVersion
    implementation 'com.finebi:fine-bi-middle:' + finebiVersion
    implementation 'com.finebi:fine-decision-bi:' + finebiVersion
    implementation 'com.finebi:fine-schedule-bi:' + finebiVersion
    implementation 'com.finebi:fine-bi-query:' + finebiVersion //Versions after 7.0.9 require
    implementation 'com.finebi:fine-bi-query-excel:' + finebiVersion //Versions after 7.0.9 require
//    implementation 'com.finebi:fine-bi-spider-cluster:' + finebiVersion
//    implementation 'com.finebi:fine-bi-spider-client:'+finebiVersion
    implementation 'com.fanruan.polars:polars-assembly:' + finePolarVersion
    implementation 'com.fr.intelligence:fine-swift:' + fineVersion
    implementation 'com.fr.intelligence:fine-accumulator:' + fineVersion
    implementation 'com.fr.report:fine-report-engine:' + fineVersion


    implementation 'org.apache.tomcat:tomcat-catalina:8.5.32'
    implementation 'org.apache.tomcat:tomcat-jasper:8.5.32'
    implementation 'mysql:mysql-connector-java:5.1.44'
    implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'org.slf4j:slf4j-simple:1.7.30'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.easymock:easymock:3.5.1'
}
sourceCompatibility = '1.8'
