<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.finebi</groupId>
    <packaging>jar</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <artifactId>plugin-decision-websocket-token</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>1.8</jdk.version>
        <fbi-version>5.1-RELEASE-SNAPSHOT</fbi-version>
        <fr-version>10.0-RELEASE-SNAPSHOT</fr-version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.finebi</groupId>
            <artifactId>fine-bi-engine-spider</artifactId>
            <version>${fbi-version}</version>
        </dependency>
        <dependency>
            <groupId>com.finebi</groupId>
            <artifactId>fine-bi-adapter</artifactId>
            <version>${fbi-version}</version>
        </dependency>
        <dependency>
            <groupId>com.finebi</groupId>
            <artifactId>fine-bi-foundation</artifactId>
            <version>${fbi-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.third</groupId>
            <artifactId>fine-third</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.core</groupId>
            <artifactId>fine-core</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.datasource</groupId>
            <artifactId>fine-datasource</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.activator</groupId>
            <artifactId>fine-activator</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.decision</groupId>
            <artifactId>fine-decision</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.webui</groupId>
            <artifactId>fine-webui</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.intelligence</groupId>
            <artifactId>fine-accumulator</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.decision</groupId>
            <artifactId>fine-decision-report</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.report</groupId>
            <artifactId>fine-report-engine</artifactId>
            <version>${fr-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fr.schedule</groupId>
            <artifactId>fine-schedule</artifactId>
            <version>${fr-version}</version>
        </dependency>

        <dependency>
            <groupId>com.fr.third.server</groupId>
            <artifactId>servlet-api</artifactId>
            <version>3.0</version>
        </dependency>
        <dependency>
            <groupId>com.fr.decision</groupId>
            <artifactId>fine-decision</artifactId>
            <version>10.0-FEATURE-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <!---如果要更改调试插件，改这里的配置就可以了-->
        <outputDirectory>${project.basedir}/target/classes</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>